### ISSUE TITLE
Adapter muss nach gewisser Zeit neu gestartet werden

### ISSUE THREAD

**Issue by tokenobi** [DEV2DEV-DE/ioBroker.jablotron#10]
EDIT: No further description given

**Comment by tokenobi** [comment]
Fehler log sieht so aus:
(ich habe die ID´s mit xxxxx ausgewechselt)

2023-12-09 04:40:33.129  - [32minfo[39m: host.xxxxxxxxxxxxxx instance system.adapter.jablotron.0 started with pid 4060
2023-12-09 04:40:35.142  - [32minfo[39m: jablotron.0 (4060) setState not processed because States database not connected
2023-12-09 04:40:36.920  - [32minfo[39m: jablotron.0 (4060) starting. Version 0.0.4 (non-npm: DEV2DEV-DE/ioBroker.jablotron#xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx) in /opt/iobroker/node_modules/iobroker.jablotron, node: v18.19.0, js-controller: 5.0.16
2023-12-09 04:40:37.486  - [32minfo[39m: jablotron.0 (4060) Logged in to jablonet api
2023-12-09 04:40:37.687  - [31merror[39m: jablotron.0 (4060) getServices: AxiosError: Request failed with status code 401
2023-12-09 04:40:37.687  - [31merror[39m: jablotron.0 (4060) getExtendedData: AxiosError: Request failed with status code 401
2023-12-09 04:40:37.687  - [31merror[39m: jablotron.0 (4060) AxiosError: Request failed with status code 401
2023-12-09 04:40:37.688  - [31merror[39m: jablotron.0 (4060) Error in onReady: Error: Not connect to jablonet.net

**Comment by DEV2DEV-DE** [comment]
Lässt sich eingrenzen, nach welcher Zeit ein Neustart notwendig ist?
Ich starte da parallel auch mal einen Langzeittest.

By the way: Wenn es sich bei "ID's" um Deine lokalen IP-Adressen handeln sollte: Die brauchst Du nicht zu anonymisieren. Die sehen bei allen gleich oder zumindest fast gleich aus (192.168.178.x). Da kann niemand etwas mit anfangen.

**Comment by tokenobi** [comment]
Mit der Zeit muss ich mal schauen ob ich das eingrenzen kann.
Mit den LAN IP Adressen ist mir das schon klar. Auch wenn das viele im Forum auch löschen ;-)
Waren wirklich ID´s die die EMA betreffen

**Comment by DEV2DEV-DE** [comment]
Die aktuelle Version 0.1.0 "schluckt" jetzt die evtl. auftretenden Timeouts beim Lesen der Daten vom Server und sollte an der Ecke stabiler sein.
Außerdem kann man in den Einstellungen jetzt wählen, welche Segmente gelesen werden sollen.

**Comment by DEV2DEV-DE** [comment]
Ist das Thema mittlerweile gelöst?

**Comment by tokenobi** [comment]
> Die aktuelle Version 0.1.0 "schluckt" jetzt die evtl. auftretenden Timeouts beim Lesen der Daten vom Server und sollte an der Ecke stabiler sein. Außerdem kann man in den Einstellungen jetzt wählen, welche Segmente gelesen werden sollen.

Die Version wird mir auch nicht unter latest angeboten

**Comment by DEV2DEV-DE** [comment]
Im Beta-Repository steht aktuell Version 0.1.1 zur Verfügung

![image](https://github.com/DEV2DEV-DE/ioBroker.jablotron/assets/95883579/b6b8e779-6ca8-4e3a-8564-9be489161895)

**Comment by tokenobi** [comment]
> Im Beta-Repository steht aktuell Version 0.1.1 zur Verfügung
> 

War zu ungeduldig, wurde mir dann doch angeboten

Leider aber keine Verbesserung

`    at async Jablotron.getExtendedData (/opt/iobroker/node_modules/iobroker.jablotron/main.js:131:21)
2023-12-24 04:40:13.877  - [31merror[39m: jablotron.0 (944) Cannot read properties of undefined (reading 'services')
2023-12-24 04:40:13.912  - [32minfo[39m: jablotron.0 (944) terminating
2023-12-24 04:40:13.912  - [33mwarn[39m: jablotron.0 (944) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-12-24 04:40:14.407  - [32minfo[39m: jablotron.0 (944) terminating
2023-12-24 04:40:46.724  - [32minfo[39m: jablotron.0 (14961) setState not processed because States database not connected
2023-12-24 04:40:47.471  - [34mdebug[39m: jablotron.0 (14961) Redis Objects: Use Redis connection: 0.0.0.0:9001
2023-12-24 04:40:47.535  - [34mdebug[39m: jablotron.0 (14961) Objects client ready ... initialize now
2023-12-24 04:40:47.537  - [34mdebug[39m: jablotron.0 (14961) Objects create System PubSub Client
2023-12-24 04:40:47.538  - [34mdebug[39m: jablotron.0 (14961) Objects create User PubSub Client
2023-12-24 04:40:47.704  - [34mdebug[39m: jablotron.0 (14961) Objects client initialize lua scripts
2023-12-24 04:40:47.716  - [34mdebug[39m: jablotron.0 (14961) Objects connected to redis: 0.0.0.0:9001
2023-12-24 04:40:47.804  - [34mdebug[39m: jablotron.0 (14961) Redis States: Use Redis connection: 0.0.0.0:9000
2023-12-24 04:40:47.873  - [34mdebug[39m: jablotron.0 (14961) States create System PubSub Client
2023-12-24 04:40:47.874  - [34mdebug[39m: jablotron.0 (14961) States create User PubSub Client
2023-12-24 04:40:48.050  - [34mdebug[39m: jablotron.0 (14961) States connected to redis: 0.0.0.0:9000
2023-12-24 04:40:48.214  - [32minfo[39m: jablotron.0 (14961) starting. Version 0.1.1 in /opt/iobroker/node_modules/iobroker.jablotron, node: v18.19.0, js-controller: 5.0.17
2023-12-24 04:40:48.225  - [34mdebug[39m: jablotron.0 (14961) Fetching new session id
2023-12-24 04:40:48.721  - [32minfo[39m: jablotron.0 (14961) Logged in to jablonet api
2023-12-24 04:40:48.721  - [34mdebug[39m: jablotron.0 (14961) Session-ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2023-12-24 04:40:48.721  - [34mdebug[39m: jablotron.0 (14961) Fetching initial data from jablonet.net
2023-12-24 04:40:48.913  - [31merror[39m: jablotron.0 (14961) getServices: AxiosError: Request failed with status code 401
2023-12-24 04:40:48.913  - [31merror[39m: jablotron.0 (14961) getExtendedData: AxiosError: Request failed with status code 401
2023-12-24 04:40:48.913  - [31merror[39m: jablotron.0 (14961) AxiosError: Request failed with status code 401
2023-12-24 04:40:48.914  - [31merror[39m: jablotron.0 (14961) Error in onReady: Error: Not connect to jablonet.net`

**Comment by DEV2DEV-DE** [comment]
`setState not processed because States database not connected`

Die anderen Adapter funktionieren in dieser Installation korrekt?

Bei @Hant0r funktioniert der Adapter offenbar völlig problemlos.

**Comment by Hant0r** [comment]
Habe ihn erhrlich gesagt aktuell nicht laufen. Hoffe die nächsten Tage wieder mehr Zeit zum Testen zu haben, dann kann ich Feedback geben 👍

**Comment by sunpower10** [comment]
Hallo,

habe selbiges Problem, dass der Adapter sich mit der Zeit (in diesem Fall nach ca. 9h) disconnected.

"Verbunden mit Gerät oder Dienst" wird rot, die anderen beiden sind grün. Bekomme im Adapter die Stati (z.B. Kontakte) nicht mehr aktualisiert wenn ich ein Fenster öffne, etc.

Danke für eure Hilfe!
===================

2024-01-18 11:03:56.478 - info: admin.0 (2033) Adapter rating updated
--
2024-01-18 12:35:07.142 - info: admin.0 (2033) Request actual repository...
2024-01-18 12:35:07.701 - info: host.ubuntuserver Updating repository "stable" under "http://download.iobroker.net/sources-dist.json"
2024-01-18 12:35:12.237 - info: admin.0 (2033) Repository received successfully.
2024-01-18 18:24:41.148 - info: admin.0 (2033) ==> Connected system.user.admin from ::ffff:192.168.18.158
2024-01-18 18:37:24.927 - info: admin.0 (2033) ==> Connected system.user.admin from ::ffff:192.168.18.158
2024-01-18 18:37:44.028 - info: admin.0 (2033) <== Disconnect system.user.admin from ::ffff:192.168.18.158
2024-01-18 18:40:48.790 - info: host.ubuntuserver stopInstance system.adapter.jablotron.0 (force=false, process=true)
2024-01-18 18:40:48.794 - info: jablotron.0 (3812) Got terminate signal TERMINATE_YOURSELF
2024-01-18 18:40:48.825 - info: jablotron.0 (3812) terminating
2024-01-18 18:40:48.826 - info: jablotron.0 (3812) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2024-01-18 18:40:48.835 - info: host.ubuntuserver stopInstance system.adapter.jablotron.0 send kill signal
2024-01-18 18:40:49.303 - info: jablotron.0 (3812) terminating
2024-01-18 18:40:49.445 - info: host.ubuntuserver instance system.adapter.jablotron.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2024-01-18 18:40:51.894 - info: host.ubuntuserver instance system.adapter.jablotron.0 started with pid 6221
2024-01-18 18:40:53.711 - info: jablotron.0 (6221) setState not processed because States database not connected
2024-01-18 18:40:54.196 - info: jablotron.0 (6221) starting. Version 0.1.1 in /opt/iobroker/node_modules/iobroker.jablotron, node: v18.19.0, js-controller: 5.0.17
2024-01-18 18:40:55.300 - info: jablotron.0 (6221) Logged in to jablonet api
2024-01-18 18:57:08.183 - info: admin.0 (2033) <== Disconnect system.user.admin from ::ffff:192.168.18.158 admin
2024-01-18 19:19:26.890 - info: admin.0 (2033) ==> Connected system.user.admin from ::ffff:192.168.18.158
2024-01-18 19:28:23.616 - info: admin.0 (2033) <== Disconnect system.user.admin from ::ffff:192.168.18.158 admin

2024-01-19 03:40:13.879 - error: jablotron.0 (6221) getServices: TypeError: Cannot read properties of undefined (reading 'services')
--
2024-01-19 03:40:13.891 - error: jablotron.0 (6221) getExtendedData: TypeError: Cannot read properties of undefined (reading 'services')
2024-01-19 03:40:13.895 - error: jablotron.0 (6221) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-19 03:40:13.895 - error: jablotron.0 (6221) unhandled promise rejection: Cannot read properties of undefined (reading 'services')
2024-01-19 03:40:13.896 - error: jablotron.0 (6221) TypeError: Cannot read properties of undefined (reading 'services')
at Jablotron.getServices (/opt/iobroker/node_modules/iobroker.jablotron/main.js:181:32)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Jablotron.getExtendedData (/opt/iobroker/node_modules/iobroker.jablotron/main.js:131:21)
2024-01-19 03:40:13.896 - error: jablotron.0 (6221) Cannot read properties of undefined (reading 'services')
2024-01-19 03:40:13.916 - info: jablotron.0 (6221) terminating
2024-01-19 03:40:13.917 - warn: jablotron.0 (6221) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-19 03:40:14.409 - info: jablotron.0 (6221) terminating
2024-01-19 03:40:14.460 - error: host.ubuntuserver instance system.adapter.jablotron.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-01-19 03:40:14.465 - info: host.ubuntuserver Restart adapter system.adapter.jablotron.0 because enabled
2024-01-19 03:40:44.503 - info: host.ubuntuserver instance system.adapter.jablotron.0 started with pid 6611
2024-01-19 03:40:45.171 - info: jablotron.0 (6611) setState not processed because States database not connected
2024-01-19 03:40:45.608 - info: jablotron.0 (6611) starting. Version 0.1.1 in /opt/iobroker/node_modules/iobroker.jablotron, node: v18.19.0, js-controller: 5.0.17
2024-01-19 03:40:46.109 - info: jablotron.0 (6611) Logged in to jablonet api
2024-01-19 03:40:46.272 - error: jablotron.0 (6611) getServices: AxiosError: Request failed with status code 401
2024-01-19 03:40:46.272 - error: jablotron.0 (6611) getExtendedData: AxiosError: Request failed with status code 401
2024-01-19 03:40:46.272 - error: jablotron.0 (6611) AxiosError: Request failed with status code 401
2024-01-19 03:40:46.274 - error: jablotron.0 (6611) Error in onReady: Error: Not connect to jablonet.net
2024-01-19 05:17:52.840 - info: admin.0 (2033) ==> Connected system.user.admin from ::ffff:192.168.18.xx
2024-01-19 05:18:17.459 - info: admin.0 (2033) <== Disconnect system.user.admin from ::ffff:192.168.18.xx admin
2024-01-19 05:24:16.165 - info: admin.0 (2033) ==> Connected system.user.admin from ::ffff:192.168.18.xx

**Comment by DEV2DEV-DE** [comment]
Das API von Jablotron scheint insgesamt reichlich empfindlich und liefert im Laufe der Zeit immer mal wieder diverse HTTP-Fehler.
Von 400 (BAD_REQUEST) bis 504 (EAI_AGAIN) ist fast alles dabei.
Ich versuche gerade, den Adapter dagegen zu "härten", indem z.B. jede Stunde eine neue Session-ID geholt wird.
Ist also aktuell "work in progress".

**Comment by sunpower10** [comment]
Jablotron Adapter v0.1.3 läuft seit Beginn an einwandfrei bei mir, gute Arbeit, danke!

**Comment by Hant0r** [comment]
Hatte bis eben noch die 1.1.2 die auch durchlief. Bin jetzt auf die 1.1.3

**Comment by DEV2DEV-DE** [comment]
Ich mache dann hier mal zu, da das Problem mittlerweile gelöst ist.
